apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: L2Advertisement
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"metallb.io/v1beta1","kind":"L2Advertisement","metadata":{"annotations":{},"name":"example","namespace":"metallb-system"}}
    creationTimestamp: "2024-09-16T02:15:49Z"
    generation: 1
    name: example
    namespace: metallb-system
    resourceVersion: "10212"
    uid: f287a784-5ebe-45f7-a5b0-a40eece0d37a
kind: List
metadata:
  resourceVersion: ""
