apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: IPAddressPool
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"metallb.io/v1beta1","kind":"IPAddressPool","metadata":{"annotations":{},"name":"first-pool","namespace":"metallb-system"},"spec":{"addresses":["100.64.88.50-100.64.88.99"]}}
    creationTimestamp: "2024-09-16T02:15:49Z"
    generation: 1
    name: first-pool
    namespace: metallb-system
    resourceVersion: "10211"
    uid: 61240b16-970a-4b1c-828a-a3f81d496ce3
  spec:
    addresses:
    - 100.64.88.50-100.64.88.99
    autoAssign: true
    avoidBuggyIPs: false
kind: List
metadata:
  resourceVersion: ""
